### ISSUE TITLE
Update the docs with Evals

### ISSUE THREAD

**Issue by Jonathan-Adly** [tjmlabs/ColiVara-docs#2]
Our Evaluations are complete. We are at state of the art level (best in the world) for retrieval. See the numbers here: https://github.com/tjmlabs/ColiVara-Eval

The goal is to heavily put these performance results front and center in our 

1. main repo readme
2. Documentation 

The idea is to build trust. The evals are our main marketing tool as an objective independent benchmark.

Resources are our eval repo, as well as pages 12-20 of the [ColPali](https://arxiv.org/pdf/2407.01449) paper where they explain what are these benchmarks are.

For visual appeal - @Meghan-ux  can help with nice charts and visuals. However, we want to move fast and it will be easier for her to take a simple chart and make it nice, than to come up with one from scratch with no context. So, a simple chart first and a solid foundation - then we we layer design improvements afterward.

**Comment by Mai-Khuu** [comment]
added Short Performance section [here](https://docs.colivara.com/), and a medium-length writeup [here](https://docs.colivara.com/getting-started/about/colivara-benchmark-evaluation) 

For interal use only, full writeup doc is [here](https://docs.google.com/document/d/1DOJV4Zt-SEOR6EFxzGunpB5kYqShk6HFtnHZdf_MExM/edit?tab=t.0#heading=h.kn103pn23bkb)
