### ISSUE TITLE
Social media highlights of evals 

### ISSUE THREAD

**Issue by Jonathan-Adly** [tjmlabs/ColiVara-docs#3]
Pending completion of read me and documentation updates. See #2

**Comment by Mai-Khuu** [comment]
full writeup is [here]. As discussed with Meghan already, I tried to make each little section more contextually complete than necessary, so they could be use as a "sound bite". They can be shorten or lengthen as needed for various purposes (blog post vs Linkedin post).

**Comment by Mai-Khuu** [comment]
I also started a google sheets [here](https://docs.google.com/spreadsheets/d/1ylosFWm5_znbUw7pJHNp0cAssobRFSarod7e-EQRdjY/edit?gid=0#gid=0) with my ideas of how to turn bits and pieces of the write up to social media posts.
