### ISSUE TITLE
Add docs on how users can set up webhooks for document upsertion

### ISSUE THREAD

**Issue by Abdullah13521** [tjmlabs/ColiVara-docs#6]
Initial draft:
Users can set up a webhook to receive notifications on for Async document upsertion, you can add a webhook to your user by sending a POST request to the /v1/webhook endpoint with the preferred url in the body. This endpoint will return your svix application id, endpoint id, and the endpoint secret (this will be needed when verifying the received webhooks).  You can also add/change webhooks through the edit account view in [Colivara.com](http://colivara.com/)

After setting this up, you will receive events on your webhook with document upsertion status. Possible events are upsert.fail or upsert.success. You can verify the webhooks using the svix libraries described [here](https://docs.svix.com/receiving/verifying-payloads/how), or using the validate_webhook method in Colivara's Python SDK.

**Comment by Mai-Khuu** [comment]
@Abdullah13521 is there a way to delete a webhook - either via the SDK or via the UI?

**Comment by Mai-Khuu** [comment]
done => https://app.gitbook.com/o/DHjMRQs4Vfjvi2m062WT/s/r0RGXIvkomMWAuxgus2N/guide/python-sdk/webhook
